<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document [

<!ELEMENT document ((source | PAGEBREAK | section_header)+)>
<!ELEMENT source (spellout+, heading, body)>

<!ELEMENT spellout (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT body (#PCDATA)>
<!ELEMENT section_header (#PCDATA)>
<!ELEMENT PAGEBREAK EMPTY>


<!ENTITY AElig "&amp;AElig;">
<!ENTITY Uuml "&amp;Uuml;">
<!ENTITY aacute "&amp;aacute;">
<!ENTITY aelig "&amp;aelig;">
<!ENTITY aelig-acute "&amp;aelig-acute;">
<!ENTITY auml "&amp;auml;">
<!ENTITY eacute "&amp;eacute;">
<!ENTITY emdash "&amp;emdash;">
<!ENTITY eth "&amp;eth;">
<!ENTITY iacute "&amp;iacute;">
<!ENTITY oacute "&amp;oacute;">
<!ENTITY ocirc "&amp;ocirc;">
<!ENTITY oelig "&amp;oelig;">
<!ENTITY ouml "&amp;ouml;">
<!ENTITY thorn "&amp;thorn;">
<!ENTITY uuml "&amp;uuml;">
<!ENTITY yogh "&amp;yogh;">

<!ATTLIST PAGEBREAK
        ID CDATA ""
>

]>

<document>

<source>
<spellout>A. D.</spellout>
<heading>A. D.</heading>
<body>
Altenglische Dichtungen der MS, H&auml;rl. 2253, herausgegeben von
K. Boddeker, Berlin, 1878.
</body>
</source>

<source>
<spellout>A. P.</spellout>
<heading>A. P.</heading>
<body>
v. Allit. Pms.
</body>
</source>

<source>
<spellout>A. R.</spellout>
<heading>A. R.</heading>
<body>
The Ancren Riwle, edited for the Camden Society
(No. lvii.) by J. Morton, 1853. Quoted by page and line.
</body>
</source>

<source>
<spellout>Abus.</spellout>
<heading>Abus.</heading>
<body>
Codex Junii 23, fol. 60, in the Bodleian Library. See
Wanley's Catalogue, p. 37, and Engl. Stud. viii. 62.
</body>
</source>

<source>
<spellout>&AElig;lf. Ep. lst </spellout>
<heading>&AElig;lf. Ep. lst </heading>
<body>
= L. &AElig;lfc. P. (q.v.).
</body>
</source>

<source>
<spellout>&AElig;lf. Test.</spellout>
<heading>&AElig;lf. Test.</heading>
<body>
&AElig;lfric on the Old Testament in Sweet's Anglo-Saxon
Reader (1st ed.).
</body>
</source>

<source>
<spellout>&AElig;lfc. Gen. Thw.</spellout>
<heading>&AElig;lfc. Gen. Thw.</heading>
<body>
The preface to Genesis in Thwaites'
edition of the Heptateuch. v. Gen.
</body>
</source>

<source>
<spellout>&AElig;lfc. Gl.</spellout>
<heading>&AElig;lfc. Gl.</heading>
<body>
Codex Junii 71, in the Bodleian Library. See
Wanley's Catalogue, p. 96. Printed by Somner (Som.)
at the end of his Dictionary, and again by Wright in
A Volume of Vocabularies (Wrt. Voc.). In the early
part of the Dictionary the page of the MS., and the page
and number of the word in Somner and in Wright are
given, but later the reference is to Wright only (Wrt.
Voc. i.).
</body>
</source>

<source>
<spellout>&AElig;lfc. Gl. Zup.</spellout>
<spellout>Zup.</spellout>
<heading>&AElig;lfc. Gl.; Zup.</heading>
<body>
&AElig;lfric's Grammatik und Glossar, herausgegeben
von Julius Zupitza, Berlin, 1880. Quoted by page and line.
</body>
</source>

<source>
<spellout>&AElig;lfc. Gr.</spellout>
<heading>&AElig;lfc. Gr.</heading>
<body>
&AElig;lfric's Grammar, referred to at first in the
edition by Somner, printed with his Dictionary (Som.),
later in that of Zupitza (Zup. v. preceding explanation).
Quoted by section of the Grammar, and by page and
line of the editions.
</body>
</source>

<source>
<spellout>&AElig;lfc. pref. Gen.</spellout>
<heading>&AElig;lfc. pref. Gen.</heading>
<body>
= &AElig;lfc. Gen. Thw.
</body>
</source>

<source>
<spellout>&AElig;lfc. T.</spellout>
<spellout>&AElig;lfc. T. Lisle.</spellout>
<heading>&AElig;lfc. T. or &AElig;lfc. T. Lisle.</heading>
<body>
A Saxon treatise concerning
the Old and New Testament. . . . Now first published in
print with English of our times by William L'Isle,
London, 1623. Quoted by page and line.
</body>
</source>

<source>
<spellout>&AElig;lfc. T. Grn.</spellout>
<heading>&AElig;lfc. T. Grn.</heading>
<body>
The same text, in vol. i. of Bibliothek der
Angels&auml;chsischen Prosa, herausgegeben von Chr. Grein. 1872.
See also &AElig;lf. Test.
</body>
</source>

<source>
<spellout>&AElig;qu. Vern.</spellout>
<heading>&AElig;qu. Vern.</heading>
<body>
This contraction (used, but not explained, by
Lye) seems to refer to the Anglo-Saxon abridgement of
Bede's De Natura Rerum in MS. Cotton. Tiberius,
B. V. (see Wanley's Catalogue, p. 216). It is printed in
Popular Treatises on Science, edited for the Historical
Society of Science by Wright, London, 1841 (Wrt.
popl. science); and again in the 3rd vol. of Cockayne's
Leechdoms (Lchdm. III). The later quotations are
taken from the latter edition. v. Equin. vern.
</body>
</source>

<source>
<spellout>Al.</spellout>
<heading>Al.</heading>
<body>
The Life of St. Alexius, edited by F, J. Furnivall,
E.E.T.S., No. 69, 1878. Quoted by line.
</body>
</source>

<source>
<spellout>Alb. resp.</spellout>
<heading>Alb. resp.</heading>
<body>
Albini responsa ad Sigewulfi interrogationes.
For a text and MSS. see Anglia, vol. vii. pp. 1 sqq.
</body>
</source>

<source>
<spellout>Ald.</spellout>
<heading>Ald.</heading>
<body>
Sancti Aldhelmi Opera, edited by J, A. Giles, Oxford,
1844. Quoted by page.
</body>
</source>

<source>
<spellout>Alex.</spellout>
<heading>Alex.</heading>
<body>
The Alliterative Romance of Alexander, edited by
J. Stevenson, Roxburghe Club, 1849. Quoted by line.
</body>
</source>

<source>
<spellout>Alex.</spellout>
<spellout>Alex. Skt.</spellout>
<heading>Alex. (Skt).</heading>
<body>
The same, edited by W. W. Skeat, E.E.T.S.,
No. lxvii., 1866. Quoted by line.
</body>
</source>

<source>
<spellout>Alis.</spellout>
<heading>Alis.</heading>
<body>
King Alisaunder, in Weber's Metrical Romances, vol. i.,
Edinburgh, 1810. Quoted by line.
</body>
</source>

<source>
<spellout>Allit. Pms.</spellout>
<heading>Allit. Pms.</heading>
<body>
Early English Alliterative Poems, edited by
R. Morris, E.E.T.S., No. 1, 1864. Quoted by page and
line.
</body>
</source>

<source>
<spellout>Am.</spellout>
<spellout>Amil.</spellout>
<heading>Am. and Amil.</heading>
<body>
Amis and Amiloun, in Weber's Metrical
Romances, vol. ii.
</body>
</source>

<source>
<spellout>An. Lit.</spellout>
<heading>An. Lit.</heading>
<body>
Anecdota Literaria, edited by Thomas Wright,
London, 1844. Quoted by page and line.
</body>
</source>

<source>
<spellout>An. Th.</spellout>
<spellout>Anal. Th.</spellout>
<spellout>Th. An.</spellout>
<spellout>Th. Anal.</spellout>
<spellout>Th. Anlct.</spellout>
<heading>An. (or Anal.) Th. or Th. An. (Anal., Anlct.).</heading>
<body>
Analecta
Anglo-Saxonica, by Benjamin Thorpe, London, 1846.
Quoted by page and line.
</body>
</source>

<source>
<spellout>And. </spellout>
<heading>And. </heading>
<body>
= St. And. (q.v.).
</body>
</source>

<source>
<spellout>Andr. Grm. </spellout>
<heading>Andr. Grm. </heading>
<body>
See Grm[m]. A. u. E.
</body>
</source>

<source>
<spellout>Andr. Kmbl.</spellout>
<heading>Andr. Kmbl.</heading>
<body>
The Poetry of the Codex Vercellensis, edited
by J. M. Kemble for the &AElig;lfric Society. Part 1. The
Legend of St. Andrew, London, 1844.
</body>
</source>

<PAGEBREAK ID="a0004"/>

<source>
<spellout>Andr. Recd.</spellout>
<heading>Andr. Recd.</heading>
<body>
The same poem edited for the Record Commission
by Benjamin Thorpe, but not published. See Glos. Epnl. Recd.
</body>
</source>

<source>
<spellout>Andrews' Old English Manor.</spellout>
<heading>Andrews' Old English Manor.</heading>
<body>
The Old English Manor,
a study in English Economic History, by Charles McLean
Andrews, Baltimore, 1892.
</body>
</source>

<source>
<spellout>Anglia.</spellout>
<heading>Anglia.</heading>
<body>
Anglia, Zeitschrift f&uuml;r Englische Philologie. Halle,
1878-
</body>
</source>

<source>
<spellout>Anlct.</spellout>
<heading>Anlct.</heading>
<body>
v. An. Th.
</body>
</source>

<source>
<spellout>Ap. Th.</spellout>
<spellout>Apol. Th.</spellout>
<spellout>Th. Ap.</spellout>
<spellout>Th. Apol.</spellout>
<heading>Ap. (Apol.) Th. or Th. Ap. (Apol.).</heading>
<body>
The Anglo-Saxon
Version of the Story of Apollonius of Tyre, from a MS.
in the Library of C. C. C., Cambridge (v. Wanley's Catalogue,
p. 146), edited by Benjamin Thorpe, London, 1834.
Quoted by page and line.
</body>
</source>

<source>
<spellout>App. Scint.</spellout>
<heading>App. (Lib.) Scint.</heading>
<body>
v. Scint.
</body>
</source>

<source>
<spellout>Apstls. Crd.</spellout>
<heading>Apstls. Crd.</heading>
<body>
An interlinear version of the Apostles' Creed
on folio 199a of the MS. referred to as Ps. Lamb. (q.v.).
</body>
</source>

<source>
<spellout>Apstls. Kmbl.</spellout>
<heading>Apstls. Kmbl.</heading>
<body>
The Fates of the Twelve Apostles in The
Poetry of the Codex Vercellensis, Part II. v. Andr, Kmbl,
</body>
</source>

<source>
<spellout>Apstls. Recd.</spellout>
<heading>Apstls. Recd.</heading>
<body>
The same poem edited for the Record Commission;
v. Andr. Recd.
</body>
</source>

<source>
<spellout>Arth. and Merl.</spellout>
<heading>Arth. and Merl.</heading>
<body>
Arthour and Merlin, a Metrical Romance
edited by W. D. Turnbull, Abbotsford Club, 1838. Quoted
by line.
</body>
</source>

<source>
<spellout>Ass. B.</spellout>
<heading>Ass. B.</heading>
<body>
Assumpcio Beate Marie, edited by J. R. Lumby,
E.E.T.S., No. 14, 1866. Quoted by line.
</body>
</source>

<source>
<spellout>Ath. Crd.</spellout>
<spellout>Athan.</spellout>
<heading>Ath. Crd. or Athan.</heading>
<body>
An interlinear version of the Athanasian
Creed, folios 200a-202b of the MS, referred to as
Ps. Lamb, (q, v.). Quoted by paragraph.
</body>
</source>

<source>
<spellout>Ayenb.</spellout>
<heading>Ayenb.</heading>
<body>
Dan Michel's Ayenbite of Inwyt, in the Kentish
Dialect, 1340, edited by R. Morris, E.E.T.S., No, 23,
1866.
</body>
</source>

<source>
<spellout>Bailey.</spellout>
<heading>Bailey.</heading>
<body>
An Universal Etymological English Dictionary,
by N. Bailey, 10th edition, London, 1742.
</body>
</source>

<source>
<spellout>Basil admn.</spellout>
<spellout>Norm.</spellout>
<heading>Basil admn.; Norm.</heading>
<body>
The Anglo-Saxon Remains of St.
Basil's Admonitio ad filium spiritualem, edited by the
Rev. Henry W. Norman, 2nd edition, London, 1849.
Quoted by chapter, and by page and line.
</body>
</source>

<source>
<spellout>Bd. de nat. rm.</spellout>
<spellout>Bd. de nat. rerum</spellout>
<heading>Bd. de nat. rm. (rerum).</heading>
<body>
See under &AElig;qu. Vern.
</body>
</source>

<source>
<spellout>Bd.</spellout>
<spellout>M.</spellout>
<heading>Bd.; M.</heading>
<body>
The Old English Version of Bede's Ecclesiastical
History of the English People, edited by Thomas
Miller, E.E.T.S., Nos. 95, 96, 1890-1891. Quoted
by book and chapter, and by page and line.
</body>
</source>

<source>
<spellout>Bd. S.</spellout>
<heading>Bd. S.</heading>
<body>
Baedae Historia Ecclesiastica a gloriosissimo veterum
Anglo-Saxonum rege Aluredo Saxonice reddita,
cura et studio Johannis Smith, Cantabrigiae, 1722.
Quoted as in previous work.
</body>
</source>

<source>
<spellout>Bd.</spellout>
<spellout>Whel.</spellout>
<spellout>Whelc.</spellout>
<spellout>Bd. Whelc.</spellout>
<heading>Bd.; Whel. (Whelc.).</heading>
<body>
Bedae Venerabilis Historia Ecclesiastica Anglorum,
Anglo-Saxonice ex versione &AElig;lfredi
Magni Gentis et Latine, cura Abrahami Wheloci, Cantabrigiae,
1644.
</body>
</source>

<source>
<spellout>Ben.</spellout>
<heading>Ben.</heading>
<body>
Vocabularium Anglo-Saxonicum, opera Th. Benson,
Oxoniae, 1701.
</body>
</source>

<source>
<spellout>Beo. Kmbl.</spellout>
<heading>Beo. Kmbl.</heading>
<body>
The Anglo-Saxon poems of Beowulf, the Traveller's
Song and the Battle of Finnesburh, edited by
John M. Kemble, 2nd edition, London, 1835.
</body>
</source>

<source>
<spellout>Beo. Th.</spellout>
<heading>Beo. Th.</heading>
<body>
The Anglo-Saxon Poem of Beowulf, edited by
Benjamin Thorpe, Oxford, 1855.
</body>
</source>

<source>
<spellout>Beves.</spellout>
<heading>Beves.</heading>
<body>
Sir Beves of Hamtune, edited by E. K&ouml;lbing,
E.E.T.S., Nos, xlvi., xlviii., 1885-1886. Quoted by line.
</body>
</source>

<source>
<spellout>Blickl. Gl.</spellout>
<spellout>Blickl. Gloss.</spellout>
<heading>Blickl. Gl. (Gloss.).</heading>
<body>
Glosses taken from a copy of the
Roman Psalter in the library at Blickling Hall. Printed
at the end of the Blickling Homilies. See next paragraph.
</body>
</source>

<source>
<spellout>Blickl. Homl.</spellout>
<spellout>Homl. Blick.</spellout>
<heading>Blickl. Homl. or Homl. Blick.</heading>
<body>
The Blickling Homilies,
edited by R. Morris, E.E.T.S., Nos. 58, 63, 1874-1876.
Quoted by page and line.
</body>
</source>

<source>
<spellout>Boutr. Scrd.</spellout>
<spellout>Btwk. Scrd.</spellout>
<heading>Boutr. (Btwk.) Scrd.</heading>
<body>
Screadunga. Anglo-Saxonica maximam
partem inedita publicavit C. G. Bouterwek, Elberfeld,
1858. Quoted by page and line.
</body>
</source>

<source>
<spellout>Brand.</spellout>
<heading>Brand.</heading>
<body>
Popular Antiquities of Great Britain, edited,
from the materials collected by John Brand, by W. C.
Hazlitt. Three vols. London, 1870.
</body>
</source>

<source>
<spellout>Bridfr.</spellout>
<spellout>Bridf.</spellout>
<heading>Bridf[r].</heading>
<body>
Bridferth's Enchiridion contained in MS. No. 328
in the Ashmolean Library (see Wanley's Catalogue,
p. 103). Quoted by folio. This MS. is printed in
Anglia viii. 298-337, and later references are to this
edition by page and line.
</body>
</source>

<source>
<spellout>Bt.</spellout>
<spellout>Fox.</spellout>
<heading>Bt.; Fox.</heading>
<body>
King Alfred's Anglo-Saxon version of Boethius
de Consolatione Philosophiae, edited by the Rev. S. Fox.
Bohn's Antiquarian Library, London, 1864. Quoted by
chapter and paragraph, and by page and line.
</body>
</source>

<source>
<spellout>Bt. Met. Fox</spellout>
<spellout>Bt. Tupr.</spellout>
<heading>Bt. Met. Fox and Bt. Tupr.</heading>
<body>
The Anglo-Saxon metrical
version of the metrical portions of Boethius, with a verse
translation by M. Tupper. At the end of the previous work. Quoted by
number of metre and line.
</body>
</source>

<source>
<spellout>Bt.</spellout>
<spellout>Rawl.</spellout>
<heading>Bt.; Rawl.</heading>
<body>
Boethii Consolationis Philosophiae libri v
Anglo-Saxonice redditi ab &AElig;lfredo; ad Apographum
Junianum expressos edidit Christophorus Rawlinson,
Oxoniae, 1698. Quoted by chapter and paragraph, and
by page and line.
</body>
</source>

<source>
<spellout>Btwk.</spellout>
<heading>Btwk.</heading>
<body>
C&aelig;dmon's Biblische Dichtungen, herausgegeben von
K. W. Bouterwek. Erster Theil, G&uuml;tersloh, 1854. The
references are to the Anglo-Saxon piece 'De officiis
diurnalium et nocturnalium horarum,' preface, pp. cxciv-ccxxii.
Quoted by page and line.
</body>
</source>

<source>
<spellout>Btwk. Scrd.</spellout>
<heading>Btwk. Scrd.</heading>
<body>
v. Boutr. Scrd.
</body>
</source>

<source>
<spellout>Byrht. Th.</spellout>
<heading>Byrht. Th.</heading>
<body>
The poem on the battle of Maldon in Thorpe's
Analecta Anglo-Saxonica. Quoted by page and line.
</body>
</source>

<source>
<spellout>C. L.</spellout>
<heading>C. L.</heading>
<body>
Castel off Love, edited by R. F. Weymouth, Philol.
Soc., 1864. Quoted by line.
</body>
</source>

<source>
<spellout>C. M.</spellout>
<heading>C. M.</heading>
<body>
Cursor Mundi, edited by R. Morris, E.E.T.S. Quoted
by line.
</body>
</source>

<source>
<spellout>C. R. Ben.</spellout>
<heading>C. R. Ben.</heading>
<body>
An Anglo-Saxon version of the Benedictine Rule
contained in a MS. in the library of Corpus Christi
College, Cambridge. See Wanley's Catalogue, p. 122.
Quoted by chapter. In the latter part of the Dictionary
references are given to the work noticed under R. Ben.,
in which this MS. is used,
</body>
</source>

<source>
<spellout>Cambr. MS. Ps.</spellout>
<heading>Cambr. MS. Ps.</heading>
<body>
= Ps. Spl. C. (q.v.).
</body>
</source>

<source>
<spellout>Canon. Hrs.</spellout>
<heading>Canon. Hrs.</heading>
<body>
Appendix to Hickes' Letters to a Popish
Priest. Quoted by page and line. The piece is printed
in Select Monuments of the Doctrine and Worship of
the Catholic Church in England before the Norman
Conquest, by E. Thompson, London, 1875 (2nd edition).
</body>
</source>

<source>
<spellout>Cant. Ab.</spellout>
<spellout>Cant. Abac.</spellout>
<spellout>Cant. Habac.</spellout>
<spellout>Cant. Abac. Lamb.</spellout>
<heading>Cant. Ab. (Abac., Habac., Abac. Lamb.).</heading>
<body>
A gloss of
Habakkuk, 3, 2-19, contained in the same MS. as Ps.
Lamb. (q. v.) on folios 189-191. Quoted by verse.
</body>
</source>

<source>
<spellout>Cant. Abac. Surt.</spellout>
<heading>Cant. Abac. Surt.</heading>
<body>
A gloss of the same material as the
preceding, printed in An Anglo-Saxon and Early English
Psalter, edited by J. Stevenson, Surtees Soc., No. 19.
Quoted by page and line.
</body>
</source>

<source>
<spellout>Cant. An.</spellout>
<spellout>Cantic. An.</spellout>
<heading>Cant. (Cantic.) An.</heading>
<body>
A gloss of the song of Hannah (I. Sam.
2, l-10), contained in the same MS. as Ps. Lamb. (q. v.)
on folios 185b - 186b. Quoted by verse.
</body>
</source>

<source>
<spellout>Cant. Es.</spellout>
<heading>Cant. Es.</heading>
<body>
A gloss of Isaiah 12, 1-6, contained in the same
MS. as the preceding, on folio 184. Quoted by verse.
</body>
</source>

<source>
<spellout>Cant. Ez.</spellout>
<spellout>Cant. Ezech. Lamb.</spellout>
<heading>Cant. Ez. (Cant. Ezech. Lamb.).</heading>
<body>
A gloss of Isaiah 38, 10-20,
contained in the same MS. as the preceding, on
folios 184b - 185b. Quoted by verse (in some instances
the folio of the MS. is also given).
</body>
</source>

<source>
<spellout>Cant. M.</spellout>
<spellout>Cant. Moys.</spellout>
<spellout>Cant. Moys. Lamb.</spellout>
<heading>Cant. M. (Moys., Moys. Lamb.).</heading>
<body>
A gloss of Exodus 15,
1-19, contained in the same MS. as the preceding, on
folios 186b - 189. Quoted as in the preceding.
</body>
</source>

<source>
<spellout>Cant. M. ad fil.</spellout>
<spellout>Cant. Moys. Isrl. Lamb.</spellout>
<heading>Cant. M. ad fil. (Moys. Isrl. Lamb.).</heading>
<body>
A gloss of Deuteronomy
32, 1-43, contained in the same MS. as the
preceding, on folios 191-195. Quoted as in the preceding.
</body>
</source>

<source>
<spellout>Cant. Mar.</spellout>
<heading>Cant. Mar.</heading>
<body>
A gloss of Luke 1, 46-55, contained in the same
MS. as the preceding, on folios 198-198b. Quoted by
verse.
</body>
</source>

<PAGEBREAK ID="a0005"/>

<source>
<spellout>Cant. Moys. Ex.</spellout>
<spellout>Cantic. Moys.</spellout>
<spellout>Thw.</spellout>
<spellout>Cant. Moys. Thw.</spellout>
<heading>Cant. Moys. Ex. (Cantic. Moys.); Thw.: Cant. Moys. Thw.</heading>
<body>
A gloss of Exodus 15, 1-19, at the end of
Thwaites' Heptateuch.
</body>
</source>

<source>
<spellout>Cant. Zach.</spellout>
<heading>Cant. Zach.</heading>
<body>
A gloss of Luke 1, 68-79, contained in the
same MS. as Ps. Lamb. (q. v.) on folios 197-198. Quoted
by verse.
</body>
</source>

<source>
<spellout>Cart. Eadgif. R.</spellout>
<heading>Cart. Eadgif. R.</heading>
<body>
A charter of Queen Eadgifu, v. Chart. Th. 201.
</body>
</source>

<source>
<spellout>Cath. Ang.</spellout>
<spellout>Cath. Angl.</spellout>
<heading>Cath. Ang. (Angl.).</heading>
<body>
Catholicon Anglicum, edited by
S. J. Herrtage, E.E.T.S., No. 75, 1881. Quoted by
page.
</body>
</source>

<source>
<spellout>Cd.</spellout>
<spellout>Th.</spellout>
<spellout>Cd. Th.</spellout>
<heading>Cd.; Th. (later Cd. Th.).</heading>
<body>
C&aelig;dmon's Metrical Paraphrase
of parts of the Holy Scripture, in Anglo-Saxon, by
Benjamin Thorpe, London, 1832. Quoted at first by
folio, and by page and line, later by page and line.
</body>
</source>

<source>
<spellout>Chart. Erl.</spellout>
<heading>Chart. Erl.</heading>
<body>
A Handbook to the Land Charters, and other
Saxonic Documents, by John Earle, M.A., Oxford, 1888.
Quoted by page and line.
</body>
</source>

<source>
<spellout>Ch. Th.</spellout>
<spellout>Chart. Th.</spellout>
<heading>Chart. (Ch.) Th.</heading>
<body>
Diplomatarium Anglicum Aevi Saxonici,
by Benjamin Thorpe, London, 1865. Quoted by page
and line.
</body>
</source>

<source>
<spellout>Chauc.</spellout>
<heading>Chauc.</heading>
<body>
The abbreviations used in connexion with Chaucer
are not given as not requiring explanation.
</body>
</source>

<source>
<spellout>Chr. Erl.</spellout>
<spellout>Chr.</spellout>
<spellout>Erl.</spellout>
<heading>Chr.; Erl.</heading>
<body>
Two of the Saxon Chronicles parallel with
supplementary extracts from the others, edited by John
Earle, M.A., Oxford, 1865. Quoted by year, and by
page and line.
</body>
</source>

<source>
<spellout>Chr.</spellout>
<spellout>Gib.</spellout>
<heading>Chr.; Gib.</heading>
<body>
Chronicon. Saxonicum, Latine et Anglo-
Saxonice, cum notis Edmundi Gibson, Oxon., 1692.
</body>
</source>

<source>
<spellout>Chr.</spellout>
<spellout>Ing.</spellout>
<heading>Chr.; Ing.</heading>
<body>
The Saxon Chronicle, with an English translation
and notes, by the Rev. James Ingram, 1833.
</body>
</source>

<source>
<spellout>Chr. Th.</spellout>
<spellout>Th.</spellout>
<heading>Chr.; Th.</heading>
<body>
The Anglo-Saxon Chronicle, according to the
several original authorities. Edited, with a translation,
by Benjamin Thorpe, Master of the Rolls Series, 1861.
Quoted by year, and by page, line, and column.
</body>
</source>

<source>
<spellout>Chron. Abing.</spellout>
<heading>Chron. Abing.</heading>
<body>
Chronicon Monasterii de Abingdon. Edited
by Rev. J. Stevenson, Master of the Rolls Series, 1858.
</body>
</source>

<source>
<spellout>Chron. Vilodun.</spellout>
<heading>Chron. Vilodun.</heading>
<body>
Chronicon Vilodunense, sive de vita et
miraculis sanctae Edithae, cur. W. H. Black. Quoted
by line.
</body>
</source>

<source>
<spellout>Cl. and Vig. Dict.</spellout>
<heading>Cl. and Vig. Dict.</heading>
<body>
An Icelandic-English Dictionary, based
on the MS. collections of the late Richard Cleasby, enlarged
and completed by Gudbrand Vigfusson, Oxford, 1874.
</body>
</source>

<source>
<spellout>Cod. Dip. B.</spellout>
<heading>Cod. Dip. B.</heading>
<body>
Cartularium Saxonicum: a collection of
Charters relating to Anglo-Saxon History, by Walter de
Gray Birch, London, 1883-1893. Quoted by volume,
page and line.
</body>
</source>

<source>
<spellout>Cod. Dip. Kmbl.</spellout>
<spellout>Cod. Dipl. Kmbl.</spellout>
<heading>Cod. Dip. (Dipl.) Kmbl.</heading>
<body>
Codex Diplomaticus Aevi
Saxonici, opera Johannis M. Kemble. Publications of
the English Historical Society, 1839-1848. Quoted by
volume, page and line.
</body>
</source>

<source>
<spellout>Cod. Exon.</spellout>
<heading>Cod. Exon.</heading>
<body>
v. Exon. Th.
</body>
</source>

<source>
<spellout>Coll. Monast.</spellout>
<spellout>Coll. Monast. Wrt.</spellout>
<heading>Coll. Monast. Th. or Wrt</heading>
<body>
Colloquium ad pueros linguae
Latinae locutione exercendos ab &AElig;lfrico compilatum.
Printed in Thorpe's Analecta (v. An. Th.), or in Wright's
Vocabularies (v. Wrt. Voc. i.). Quoted by page and line.
</body>
</source>

<source>
<spellout>Confess. Pecc.</spellout>
<spellout>Confess. Peccat.</spellout>
<heading>Confess. Pecc. (Peccat.).</heading>
<body>
A gloss of a 'Confessio pro
peccatis ad Deum,' contained in the same MS. as Ps.
Lamb, (q.v.) on folios 182b - 183 b.
</body>
</source>

<source>
<spellout>Corp. Gl. Hessels.</spellout>
<spellout>Corp. Gl. ed. Hessels.</spellout>
<spellout>Corp. Gl. H.</spellout>
<heading>Corp. Gl. (ed.) Hessels.</heading>
<body>
An eighth-century Latin-Anglo-Saxon
Glossary preserved in the Library of Corpus
Christi College, Cambridge, edited by J. H. Hessels,
Cambridge, 1890. Quoted by page and number of word.
</body>
</source>

<source>
<spellout>Cot.</spellout>
<heading>Cot.</heading>
<body>
In the earlier part of the Dictionary several glossaries
found among the Cotton MSS. are referred to by this
abbreviation. These glossaries are printed in Wrt. Voc.
i., ii., to which works later references are given; in
a supplement to the Dictionary similar references will be
found to replace the abbreviation in question.
</body>
</source>

<source>
<spellout>D. Arth.</spellout>
<heading>D. Arth.</heading>
<body>
Morte Arthure; or the Death of Arthur, edited by
Edm. Brock, E.E.T.S., No. 8, 1871. Quoted by line.
</body>
</source>

<source>
<spellout>Dep. Rich.</spellout>
<heading>Dep. Rich.</heading>
<body>
Richard the Redeles, an Alliterative Poem on
the Deposition of Richard II, edited by W. W. Skeat,
E.E.T.S., No. 54, 1873. Quoted by passus and line.
</body>
</source>

<source>
<spellout>Destr. Tr.</spellout>
<heading>Destr. Tr.</heading>
<body>
The Gest Historiale of the Destruction of Troy,
edited by G. A. Panton and D. Donaldson, E.E.T.S.,
Nos. 39, 56. Quoted by line.
</body>
</source>

<source>
<spellout>Deut.</spellout>
<heading>Deut.</heading>
<body>
The Anglo-Saxon version of Deuteronomy in Thw.
Hept. (q.v.) or in Bibliothek der Angels&auml;chsischen
Prosa, herausgegeben von Chr. Wilh. Mich. Grein,
erster Band, 1872. Quoted by chapter and verse.
</body>
</source>

<source>
<spellout>Dial.</spellout>
<heading>Dial.</heading>
<body>
v. Gr. Dial.
</body>
</source>

<source>
<spellout>Dief.</spellout>
<heading>Dief.</heading>
<body>
Vergleichendes W&ouml;rterbuch der Gothischen Sprache,
von Dr. Lorenz Diefenbach, 1851.
</body>
</source>

<source>
<spellout>Dietr.</spellout>
<heading>Dietr.</heading>
<body>
Dietrich's Commentatio de Kynewulfi poetae aetate,
Marburg, 1859 - 1860.
</body>
</source>

<source>
<spellout>D&oacute;m. L.</spellout>
<heading>D&oacute;m. L.</heading>
<body>
Be D&oacute;mes D&aelig;ge, an Old English version of the
Latin poem ascribed to Bede. Edited with other short
poems from the MS. in the Library of Corpus Christi
College, Cambridge, by J. R. Lumby, E.E.T.S., No. 65,
1876. Quoted by page and line.
</body>
</source>

<source>
<spellout>E. D. S.</spellout>
<heading>E. D. S. (Publ.).</heading>
<body>
The publications of the English Dialect Society.
</body>
</source>

<source>
<spellout>E. E. T. S.</spellout>
<heading>E. E. T. S.</heading>
<body>
The publications of the Early English Text Society.
</body>
</source>

<source>
<spellout>E. G.</spellout>
<heading>E. G.</heading>
<body>
English Gilds, edited by Miss L. Toulmin Smith,
E.E.T.S., No. 40, 1870. Quoted by page and line.
</body>
</source>

<source>
<spellout>Earle A. S. Lit.</spellout>
<heading>Earle A. S. Lit.</heading>
<body>
Anglo-Saxon Literature. By John Earle.
London: Society for Promoting Christian Knowledge,
1884.
</body>
</source>

<source>
<spellout>Ecclus.</spellout>
<heading>Ecclus.</heading>
<body>
The book of Ecclesiasticus.
</body>
</source>

<source>
<spellout>Elen. Grm.</spellout>
<heading>Elen. Grm.</heading>
<body>
v. Grmm. A. u. E.
</body>
</source>

<source>
<spellout>Elen. Kmbl.</spellout>
<heading>Elen. Kmbl.</heading>
<body>
The Poetry of the Codex Vercellensis, edited
for the &AElig;lfric Society by J. M. Kemble. Part II. Elene
and Minor Poems, London, 1856.
</body>
</source>

<source>
<spellout>Engl. Stud.</spellout>
<heading>Engl. Stud.</heading>
<body>
Englische Studien. Organ f&uuml;r englische
Philologie. Herausgegeben von Dr. Eugen K&ouml;lbing.
</body>
</source>

<source>
<spellout>Ep. Gl.</spellout>
<spellout>Gloss. Ep.</spellout>
<heading>Ep. Gl. (Gloss. Ep.).</heading>
<body>
The Epinal Glossary, Latin and Old-English
of the eighth century. Edited by Henry Sweet.
Printed for the Philological and Early English Text
Societies, 1883. Quoted by page, column and line.
</body>
</source>

<source>
<spellout>Equin. vern.</spellout>
<heading>Equin. vern.</heading>
<body>
An Anglo-Saxon summary of Bede's De
Temporibus, referred to in Wanley's Catalogue under
the heading De equinoctio vernali. It is printed in
Lchdm. iii. pp. 232-280, and the quotations from the
work are, except in the earlier part of the Dictionary,
from this printed form. v. &AElig;qu. Vern.
</body>
</source>

<source>
<spellout>Erf. Gl.</spellout>
<heading>Erf. Gl.</heading>
<body>
A Latin-Anglo-Saxon Glossary contained in a MS.
preserved in the Amplomian library at Erfurt. Printed
in the oldest English Texts, edited by Henry Sweet,
E.E.T.S., No. 83, 1885.
</body>
</source>

<source>
<spellout>Ettm.</spellout>
<heading>Ettm.</heading>
<body>
Lexicon Anglosaxonicum, edidit Ludovicus Ettm&uuml;llerus.
Quedlinburgii. et Lipsiae, 1851.
</body>
</source>

<source>
<spellout>Ettm. Poet.</spellout>
<heading>Ettm. Poet.</heading>
<body>
Anglosaxonum poetae atque scriptores prosaici.
Edidit Ludovicus Ettm&uuml;llerus. Quedlinburgii et Lipsiae, 1850.
</body>
</source>

<source>
<spellout>Ex.</spellout>
<heading>Ex.</heading>
<body>
The Anglo-Saxon version of Exodus, v. Deut.
</body>
</source>

<source>
<spellout>Exod. Thw.</spellout>
<heading>Exod. Thw.</heading>
<body>
v. preceding.
</body>
</source>

<source>
<spellout>Exon.</spellout>
<spellout>Th.</spellout>
<spellout>Exon. Th.</spellout>
<heading>Exon.; Th. (later Exon. Th.).</heading>
<body>
Codex Exoniensis. A
Collection of Anglo-Saxon poetry, from a MS. in the
library of the Dean and Chapter of Exeter, by Benjamin
Thorpe, London, 1842; Quoted at first by folio, and by
page and line, later by page and line.
</body>
</source>

<source>
<spellout>Fer.</spellout>
<heading>Fer.</heading>
<body>
Sir Ferumbras, edited by S. J. Herrtage, E.E.T.S.,
No. xxiv., 1879. Quoted by line.
</body>
</source>

<PAGEBREAK ID="a0006"/>

<source>
<spellout>Fins. Th.</spellout>
<heading>Fins. Th.</heading>
<body>
The Anglo-Saxon poem of the Fight at Finnesburg,
edited by Benjamin Thorpe. In the same volume
with Beo. Th. (q.v.).
</body>
</source>

<source>
<spellout>Fl. a. Bl.</spellout>
<heading>Fl. a. Bl.</heading>
<body>
Floriz and Blauncheflur, edited by J. R. Lumby,
E.E.T.S., No. 14, 1866. Quoted by line.
</body>
</source>

<source>
<spellout>Frag. Kmbl.</spellout>
<heading>Frag. Kmbl.</heading>
<body>
A Fragment, Moral and Religious, contained
in the Poetry of the Codex Vercellensis, edited by J. M.
Kemble (v. Elen. Kmbl.).
</body>
</source>
